import { expect, test, type Page } from '@playwright/test';

async function load(page: Page, id: string, title: string) {
  await page.getByRole('button', { name: 'Examples', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Example library' });
  await expect(dialog).toBeVisible();
  await dialog.getByLabel('Choose an example').selectOption(id);
  await dialog.getByRole('button', { name: 'Load example', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.frameLocator('#preview-frame').getByRole('heading', { name: title, exact: true })).toBeVisible();
}

test('examples render props, native events, independent nested state, and async recovery', async ({ page }) => {
  await page.goto('/');
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const preview = page.frameLocator('#preview-frame');
  await expect(preview.getByRole('heading', { name: 'Hello, world.' })).toBeVisible();
  await load(page, 'props', 'Props & components');
  await preview.getByLabel('Your name').fill('Lin');
  await expect(preview.getByRole('heading', { name: 'Hello, Lin!' })).toBeVisible();
  await expect(preview.getByRole('heading', { name: 'Hello, Grace!' })).toBeVisible();
  await load(page, 'events', 'State & events');
  await expect(preview.getByText('No ideas yet.')).toBeVisible();
  await preview.getByLabel('New idea').fill('Build a compiler');
  await preview.getByLabel('New idea').press('Enter');
  await expect(preview.getByRole('listitem')).toHaveText(['Build a compiler']);
  await preview.getByLabel('New idea').fill('Build a compiler');
  await preview.getByRole('button', { name: 'Add idea' }).click();
  await expect(preview.getByRole('listitem')).toHaveCount(1);
  await preview.getByRole('button', { name: 'Clear ideas' }).click();
  await expect(preview.getByText('No ideas yet.')).toBeVisible();
  await load(page, 'nested-components', 'Nested components');
  await preview.getByRole('button', { name: 'Applaud Ada' }).click();
  await preview.getByRole('button', { name: 'Applaud Ada' }).click();
  await expect(preview.getByRole('article').filter({ has: preview.getByRole('heading', { name: 'Ada', exact: true }) })).toContainText('2 applause');
  await expect(preview.getByRole('article').filter({ has: preview.getByRole('heading', { name: 'Grace', exact: true }) })).toContainText('0 applause');
  await load(page, 'async', 'Async loading & recovery');
  await preview.getByRole('button', { name: 'Simulate failure' }).click();
  await expect(preview.getByRole('status')).toHaveText('Loading message…');
  await expect(preview.getByRole('button', { name: 'Load message' })).toBeDisabled();
  await expect(preview.getByRole('alert')).toContainText('The simulated request failed.');
  await preview.getByRole('button', { name: 'Load message' }).click();
  await expect(preview.getByRole('status')).toHaveText('Your async message has arrived.');
  await load(page, 'hello-world', 'Hello, world.');
  await preview.getByRole('button', { name: 'Increase count' }).click();
  await expect(preview.locator('.value')).toHaveText('1');
  expect(errors).toEqual([]);
});

test('example review protects edits; loading replaces cached files and survives reload on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  const editor = page.getByRole('textbox', { name: 'Source editor' });
  await expect(editor).toBeVisible();
  await editor.focus();
  await page.keyboard.press('ControlOrMeta+a');
  await page.keyboard.insertText('h1 My current work\n');
  await expect(page.frameLocator('#preview-frame').getByRole('heading', { name: 'My current work' })).toBeVisible();
  await page.getByRole('button', { name: 'Examples', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Example library' });
  await dialog.getByLabel('Choose an example').selectOption('props');
  await dialog.getByText('/src/Greeting.btsx', { exact: true }).click();
  await expect(dialog.locator('pre').filter({ hasText: 'props { name, role }' })).toBeVisible();
  await page.screenshot({ path: 'test-results/examples-mobile.png', fullPage: true });
  await dialog.getByRole('button', { name: 'Keep current project' }).click();
  await expect(editor).toContainText('My current work');
  await page.getByRole('button', { name: 'Examples', exact: true }).click();
  await expect(dialog).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(editor).toContainText('My current work');
  await load(page, 'props', 'Props & components');
  await editor.focus();
  await page.keyboard.press('ControlOrMeta+z');
  await expect(editor).not.toContainText('My current work');
  await expect(page.getByRole('tab', { name: 'Counter.btsx', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.frameLocator('#preview-frame').getByRole('heading', { name: 'Props & components', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('reducer recipe supports undo, redo, and branching history', async ({ page }) => {
  await page.goto('/');
  await load(page, 'reducer-history', 'Reducer & undo history');
  const preview = page.frameLocator('#preview-frame');
  const count = preview.getByRole('status');
  const undo = preview.getByRole('button', { name: 'Undo', exact: true });
  const redo = preview.getByRole('button', { name: 'Redo', exact: true });
  await expect(count).toHaveText('Count: 0');
  await expect(undo).toBeDisabled();
  await expect(redo).toBeDisabled();
  await preview.getByRole('button', { name: 'Increase', exact: true }).click();
  await preview.getByRole('button', { name: 'Increase', exact: true }).click();
  await expect(count).toHaveText('Count: 2');
  await undo.click();
  await expect(count).toHaveText('Count: 1');
  await redo.click();
  await expect(count).toHaveText('Count: 2');
  await undo.click();
  await preview.getByRole('button', { name: 'Decrease', exact: true }).click();
  await expect(count).toHaveText('Count: 0');
  await expect(redo).toBeDisabled();
  await undo.click();
  await expect(count).toHaveText('Count: 1');
  await undo.click();
  await expect(count).toHaveText('Count: 0');
  await expect(undo).toBeDisabled();
});

test('context recipe updates consumers while preserving nested overrides and defaults', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await load(page, 'context', 'Context & nested providers');
  const preview = page.frameLocator('#preview-frame');
  const card = (name: string) => preview.getByRole('article').filter({ has: preview.getByRole('heading', { name, exact: true }) });
  await expect(card('Shared preference')).toContainText('Density: comfortable');
  await expect(card('Shared preference')).toHaveCSS('padding-top', '24px');
  await expect(card('Nested override')).toContainText('Density: compact');
  await expect(card('Outside provider')).toContainText('Density: comfortable');
  await preview.getByRole('button', { name: 'Toggle density' }).click();
  await expect(card('Shared preference')).toContainText('Density: compact');
  await expect(card('Shared preference')).toHaveCSS('padding-top', '8px');
  await expect(card('Nested override')).toContainText('Density: compact');
  await expect(card('Outside provider')).toContainText('Density: comfortable');
  await preview.getByRole('button', { name: 'Toggle density' }).click();
  await expect(card('Shared preference')).toContainText('Density: comfortable');
  const frame = page.frames().find(frame => frame.parentFrame())!;
  expect(await frame.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/advanced-context-mobile.png', fullPage: true });
  await page.reload();
  await expect(preview.getByRole('heading', { name: 'Context & nested providers', exact: true })).toBeVisible();
});

test('effect recipe removes listeners on unmount and reconnects without duplicate subscriptions', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await load(page, 'effect-cleanup', 'Effects & subscription cleanup');
  const preview = page.frameLocator('#preview-frame');
  const received = page.locator('#console-list').getByText('Listener received a signal.', { exact: true });
  await expect(page.locator('#console-list')).toContainText('Listener connected.');
  await preview.getByRole('button', { name: 'Send signal' }).click();
  await expect(preview.getByRole('status')).toHaveText('Signals received: 1');
  await expect(received).toHaveCount(1);
  await preview.getByRole('button', { name: 'Hide listener' }).click();
  await expect(page.locator('#console-list')).toContainText('Listener disconnected.');
  await expect(preview.getByRole('status')).toHaveText('Listener is unmounted.');
  await preview.getByRole('button', { name: 'Send signal' }).click();
  const frame = page.frames().find(frame => frame.parentFrame())!;
  await frame.evaluate(() => console.info('Hidden signal finished.'));
  await expect(page.locator('#console-list')).toContainText('Hidden signal finished.');
  await expect(received).toHaveCount(1);
  await preview.getByRole('button', { name: 'Show listener' }).click();
  await expect(preview.getByRole('status')).toHaveText('Signals received: 0');
  await expect(page.locator('#console-list').getByText('Listener connected.', { exact: true })).toHaveCount(2);
  await preview.getByRole('button', { name: 'Send signal' }).click();
  await expect(preview.getByRole('status')).toHaveText('Signals received: 1');
  await expect(received).toHaveCount(2);
  expect(errors).toEqual([]);
});
