import { expect, test } from '@playwright/test';

test('Fullstack store browses, installs, persists a bag and checks out', async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/playground');
  await expect(page.frameLocator('#preview-frame').getByRole('heading', { name: 'Hello, world.' })).toBeVisible();
  await page.getByRole('button', { name: 'Design Studio', exact: true }).click();
  await page.getByRole('tab', { name: 'Fullstack', exact: true }).click();
  await page.getByRole('button', { name: 'Explore Form Supply' }).click();
  const dialog = page.getByRole('dialog', { name: 'Fullstack app preview', exact: true });
  const shop = dialog.frameLocator('iframe');
  await expect(shop.locator('.product-card')).toHaveCount(36, { timeout: 30000 });
  await page.screenshot({ path: '/tmp/fullstack-desktop.png' });
  await shop.getByRole('button', { name: 'Grippers 6', exact: true }).click();
  await expect(shop.locator('.product-card')).toHaveCount(6);
  await shop.getByRole('button', { name: 'All 36', exact: true }).click();
  await shop.getByRole('searchbox').fill('Arc desktop');
  await expect(shop.locator('.product-card')).toHaveCount(1);
  await shop.getByRole('button', { name: 'View Arc desktop arm', exact: true }).click();
  await expect(shop.getByRole('dialog', { name: 'Product details' })).toBeVisible();
  await shop.getByRole('dialog', { name: 'Product details' }).getByRole('button', { name: 'Add to bag +', exact: true }).click();
  await expect(shop.getByRole('button', { name: 'View bag (1)' })).toBeVisible();
  await shop.getByRole('button', { name: 'Close product details' }).click();
  await dialog.getByRole('button', { name: 'Mobile preview' }).click();
  await expect.poll(() => shop.locator('body').evaluate(element => element.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/fullstack-mobile.png' });
  await dialog.getByRole('button', { name: 'Use this app' }).click();
  await dialog.getByRole('button', { name: 'Replace project with Form Supply' }).click();
  const installed = page.frameLocator('#preview-frame');
  await expect(installed.getByRole('button', { name: 'Open bag, 1 items' })).toBeVisible({ timeout: 30000 });
  await page.reload();
  await expect(installed.getByRole('button', { name: 'Open bag, 1 items' })).toBeVisible({ timeout: 30000 });
  await installed.getByRole('button', { name: 'Open bag, 1 items' }).click();
  await installed.getByRole('button', { name: 'Increase Arc desktop arm' }).click();
  await expect(installed.getByLabel('Quantity of Arc desktop arm')).toHaveText('2');
  await installed.getByLabel('Delivery method').selectOption('express');
  await installed.getByRole('button', { name: 'Place demo order' }).click();
  await expect(installed.locator('.order-confirmation')).toBeVisible();
  expect(errors).toEqual([]);
});
