import { expect, test } from '@playwright/test';

test('Margin Notes saves a reading shelf, restores its bag, and places a demo order', async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/playground');
  await expect(page.frameLocator('#preview-frame').getByRole('heading', { name: 'Hello, world.' })).toBeVisible();
  await page.getByRole('button', { name: 'Design Studio', exact: true }).click();
  await page.getByRole('tab', { name: 'Fullstack', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Explore Form Supply' })).toBeVisible();
  await page.getByRole('button', { name: 'Explore Margin Notes' }).click();
  const dialog = page.getByRole('dialog', { name: 'Fullstack app preview', exact: true });
  const shop = dialog.frameLocator('iframe');
  await expect(shop.locator('.book-card')).toHaveCount(24, { timeout: 30000 });
  await page.screenshot({ path: '/tmp/margin-desktop.png' });
  await shop.getByRole('button', { name: 'Poetry', exact: true }).click();
  await expect(shop.locator('.book-card')).toHaveCount(6);
  await shop.getByRole('button', { name: 'All', exact: true }).click();
  await shop.getByRole('searchbox', { name: 'Search books' }).fill('Elias');
  await expect(shop.locator('.book-card')).toHaveCount(1);
  await shop.getByRole('button', { name: 'Save The Quiet Move', exact: true }).click();
  await expect(shop.getByRole('button', { name: 'Unsave The Quiet Move', exact: true })).toBeVisible();
  await shop.getByRole('button', { name: 'View The Quiet Move', exact: true }).click();
  const details = shop.getByRole('dialog', { name: 'Product details' });
  await details.getByRole('button', { name: 'Read a sample' }).click();
  await expect(details.getByRole('region', { name: 'Reading sample' })).toContainText('a better question');
  await details.getByRole('button', { name: 'Add to bag +', exact: true }).click();
  await expect(details.getByRole('button', { name: 'View bag (1)' })).toBeVisible();
  await details.getByRole('button', { name: 'Close product details' }).click();
  await dialog.getByRole('button', { name: 'Mobile preview' }).click();
  await expect.poll(() => shop.locator('body').evaluate(element => element.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/margin-mobile.png' });
  await dialog.getByRole('button', { name: 'Use this app' }).click();
  await dialog.getByRole('button', { name: 'Replace project with Margin Notes' }).click();
  const installed = page.frameLocator('#preview-frame');
  await expect(installed.getByRole('button', { name: 'Open bag, 1 items' })).toBeVisible({ timeout: 30000 });
  await page.reload();
  await expect(installed.getByRole('button', { name: 'Open bag, 1 items' })).toBeVisible({ timeout: 30000 });
  await installed.getByRole('button', { name: 'Reading shelf (1)' }).click();
  await expect(installed.locator('.book-card')).toHaveCount(1);
  await installed.getByRole('button', { name: 'Open bag, 1 items' }).click();
  await installed.getByRole('button', { name: 'Increase The Quiet Move' }).click();
  await expect(installed.getByLabel('Quantity of The Quiet Move')).toHaveText('2');
  await installed.getByLabel('Delivery method').selectOption('express');
  await expect(installed.locator('.grand-total')).toContainText('$56');
  await installed.getByRole('button', { name: 'Place demo order' }).click();
  await expect(installed.locator('.order-confirmation')).toContainText('A new chapter, confirmed.');
  expect(errors).toEqual([]);
});
