import { build } from 'esbuild';
import { parseEnv } from 'node:util';
import { compile } from 'octane/compiler';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve, basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Bundle the installed production runtime once. Splitting preserves singleton identity.
const entries = {
  octane: 'octane',
  'tanstack-form': '@octanejs/tanstack-form',
  'internal-client': 'octane/internal/client',
  signals: 'octane/signals',
  'signals-client': 'octane/signals/client',
  hydration: 'octane/hydration',
  profiling: 'octane/profiling',
  'tsrx-iterable': 'octane/tsrx-iterable',
  'tsrx-spread': 'octane/tsrx-spread',
};
const result = await build({
  entryPoints: Object.fromEntries(Object.entries(entries).map(([name, specifier]) => [name, fileURLToPath(import.meta.resolve(specifier))])),
  outdir: resolve('.runtime-build'), bundle: true, splitting: true, format: 'esm',
  platform: 'browser', target: 'es2022', minify: true, write: false,
  define: { 'process.env.NODE_ENV': '"production"' },
  plugins: [{ name: 'octane-adapters', setup(build) {
    build.onLoad({ filter: /\.tsrx$/ }, async ({ path }) => ({
      contents: compile(await readFile(path, 'utf8'), path, { dev: false }).code,
      loader: 'js', resolveDir: dirname(path),
    }));
  } }],
});
const modules = result.outputFiles.map(file => ({ id: `/@runtime/${basename(file.path)}`, code: file.text }));
const imports = Object.fromEntries(Object.entries(entries).map(([name, specifier]) => [specifier, `/@runtime/${name}.js`]));
await mkdir('src/generated', { recursive: true });
await writeFile('src/generated/runtime.ts', `// Generated by scripts/prepare-runtime.mjs; do not edit.\nexport const runtimeModules = ${JSON.stringify(modules)};\nexport const runtimeImports: Record<string, string> = ${JSON.stringify(imports)};\n`);
console.log(`Prepared ${modules.length} runtime modules from installed Octane.`);

// Project stylesheets may import Tailwind; the compiler resolves these without a filesystem.
const tailwindRoot = dirname(dirname(fileURLToPath(import.meta.resolve('tailwindcss'))));
const tailwindStylesheets = {};
for (const [id, file] of [['tailwindcss', 'index.css'], ['tailwindcss/theme.css', 'theme.css'],
  ['tailwindcss/preflight.css', 'preflight.css'], ['tailwindcss/utilities.css', 'utilities.css']]) {
  tailwindStylesheets[id] = await readFile(join(tailwindRoot, file), 'utf8');
}
await writeFile('src/generated/tailwind.ts', `// Generated by scripts/prepare-runtime.mjs; do not edit.\nexport const tailwindStylesheets: Record<string, string> = ${JSON.stringify(tailwindStylesheets)};\n`);
console.log('Prepared Tailwind stylesheets for project CSS.');

// The same bootstrap powers srcdoc and the independently deployable static page.
const previewBundle = await build({ entryPoints: ['src/playground/preview-bootstrap.ts'],
  bundle: true, format: 'esm', platform: 'browser', target: 'es2022', write: false });
const { hostedPreviewDocument } = await import(`data:text/javascript;base64,${Buffer.from(previewBundle.outputFiles[0].text).toString('base64')}`);
await mkdir('public', { recursive: true });
const publicEnv = {};
for (const file of ['.env', '.env.local']) {
  try { Object.assign(publicEnv, parseEnv(await readFile(file, 'utf8'))); }
  catch (error) { if (error.code !== 'ENOENT') throw error; }
}
await writeFile('public/preview.html', hostedPreviewDocument(process.env.PUBLIC_CONVEX_URL ?? publicEnv.PUBLIC_CONVEX_URL ?? ''));
console.log('Prepared static hosted preview at public/preview.html.');

// The chat server injects the vendored Beast skill's references into its prompt. Bundled as a module, so the server
// needs no filesystem and runs unchanged in Node and in a Cloudflare Worker.
const skillRoot = resolve('.agents/skills/beast/references');
const skillReferences = {};
for (const name of (await readdir(skillRoot)).filter(name => name.endsWith('.md')).sort()) {
  skillReferences[name] = (await readFile(join(skillRoot, name), 'utf8')).trim();
}
await writeFile('src/generated/beast-skill-references.ts', `// Generated by scripts/prepare-runtime.mjs; do not edit.\nexport const beastSkillReferences: Record<string, string> = ${JSON.stringify(skillReferences)};\n`);
console.log(`Prepared ${Object.keys(skillReferences).length} Beast skill references for the chat server.`);

// Fullstack examples ship editable source, including their backend, without executing it in the editor bundle.
const storeTemplates = 'src/playground/fullstack/templates';
const storeFiles = {};
for (const file of (await readdir(storeTemplates)).filter(file => file.endsWith('.txt')).sort()) {
  storeFiles['/src/' + file.slice(0, -4)] = await readFile(join(storeTemplates, file), 'utf8');
}
for (const file of ['storeDemo.ts', 'storeDemoValidators.ts']) {
  storeFiles['/convex/' + file] = (await readFile('convex/' + file, 'utf8')).replace("'../src/playground/fullstack/products'", "'./seedData'");
}
storeFiles['/convex/seedData.ts'] = await readFile('src/playground/fullstack/products.ts', 'utf8');
await writeFile('src/generated/fullstack.ts', `// Generated by scripts/prepare-runtime.mjs; edit the fullstack templates or backend sources.\nexport const storeFiles: Record<string, string> = ${JSON.stringify(storeFiles)};\n`);
console.log('Prepared Form Supply fullstack example sources.');

const marginFiles = {};
for (const file of (await readdir('src/playground/fullstack/margin/templates')).filter(file => file.endsWith('.txt')).sort()) {
  marginFiles['/src/' + file.slice(0, -4)] = await readFile(join('src/playground/fullstack/margin/templates', file), 'utf8');
}
marginFiles['/convex/marginDemo.ts'] = (await readFile('convex/marginDemo.ts', 'utf8')).replace("'../src/playground/fullstack/margin/books'", "'./seedData'");
marginFiles['/convex/storeDemoValidators.ts'] = await readFile('convex/storeDemoValidators.ts', 'utf8');
marginFiles['/convex/seedData.ts'] = await readFile('src/playground/fullstack/margin/books.ts', 'utf8');
await writeFile('src/generated/margin.ts', `// Generated by scripts/prepare-runtime.mjs.\nexport const marginFiles: Record<string, string> = ${JSON.stringify(marginFiles)};\n`);
console.log('Prepared Margin Notes fullstack example sources.');
