import { build } from 'esbuild';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve, basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Bundle the installed production runtime once. Splitting preserves singleton identity.
const entries = {
  octane: 'octane',
  'internal-client': 'octane/internal/client',
  signals: 'octane/signals',
  'signals-client': 'octane/signals/client',
  hydration: 'octane/hydration',
  profiling: 'octane/profiling',
  'tsrx-iterable': 'octane/tsrx-iterable',
  'tsrx-spread': 'octane/tsrx-spread',
};
const result = await build({
  entryPoints: Object.fromEntries(Object.entries(entries).map(([name, specifier]) => [name, fileURLToPath(import.meta.resolve(specifier))])),
  outdir: resolve('.runtime-build'), bundle: true, splitting: true, format: 'esm',
  platform: 'browser', target: 'es2022', minify: true, write: false,
  define: { 'process.env.NODE_ENV': '"production"' },
});
const modules = result.outputFiles.map(file => ({ id: `/@runtime/${basename(file.path)}`, code: file.text }));
const imports = Object.fromEntries(Object.entries(entries).map(([name, specifier]) => [specifier, `/@runtime/${name}.js`]));
await mkdir('src/generated', { recursive: true });
await writeFile('src/generated/runtime.ts', `// Generated by scripts/prepare-runtime.mjs; do not edit.\nexport const runtimeModules = ${JSON.stringify(modules)};\nexport const runtimeImports: Record<string, string> = ${JSON.stringify(imports)};\n`);
console.log(`Prepared ${modules.length} runtime modules from installed Octane.`);

// Project stylesheets may import Tailwind; the compiler resolves these without a filesystem.
const tailwindRoot = dirname(dirname(fileURLToPath(import.meta.resolve('tailwindcss'))));
const tailwindStylesheets = {};
for (const [id, file] of [['tailwindcss', 'index.css'], ['tailwindcss/theme.css', 'theme.css'],
  ['tailwindcss/preflight.css', 'preflight.css'], ['tailwindcss/utilities.css', 'utilities.css']]) {
  tailwindStylesheets[id] = await readFile(join(tailwindRoot, file), 'utf8');
}
await writeFile('src/generated/tailwind.ts', `// Generated by scripts/prepare-runtime.mjs; do not edit.\nexport const tailwindStylesheets: Record<string, string> = ${JSON.stringify(tailwindStylesheets)};\n`);
console.log('Prepared Tailwind stylesheets for project CSS.');

// The same bootstrap powers srcdoc and the independently deployable static page.
const previewBundle = await build({ entryPoints: ['src/playground/preview-bootstrap.ts'],
  bundle: true, format: 'esm', platform: 'browser', target: 'es2022', write: false });
const { hostedPreviewDocument } = await import(`data:text/javascript;base64,${Buffer.from(previewBundle.outputFiles[0].text).toString('base64')}`);
await mkdir('public', { recursive: true });
await writeFile('public/preview.html', hostedPreviewDocument());
console.log('Prepared static hosted preview at public/preview.html.');

// The chat server injects the vendored Beast skill's references into its prompt. Bundled as a module, so the server
// needs no filesystem and runs unchanged in Node and in a Cloudflare Worker.
const skillRoot = resolve('.agents/skills/beast/references');
const skillReferences = {};
for (const name of (await readdir(skillRoot)).filter(name => name.endsWith('.md')).sort()) {
  skillReferences[name] = (await readFile(join(skillRoot, name), 'utf8')).trim();
}
await writeFile('src/generated/beast-skill-references.ts', `// Generated by scripts/prepare-runtime.mjs; do not edit.\nexport const beastSkillReferences: Record<string, string> = ${JSON.stringify(skillReferences)};\n`);
console.log(`Prepared ${Object.keys(skillReferences).length} Beast skill references for the chat server.`);
